spring.application.name=userr-demo
#server.pot=8080;
spring.datasource.url=jdbc:mysql://localhost:3306/springboot

spring.datasource.username=root

spring.datasource.password=MYSQL@123

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
#shows query in console